app7/config/routes.rb
Rails.application.routes.draw do
  resources :parts
  resources :assemblies
  resources :authors
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app7/app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
end

app7/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:name)
    end
end

app7/app/helpers/parts_helper.rb
module PartsHelper
end

app7/app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app7/app/views/parts/_part.html.erb
<div id="<%= dom_id part %>">
  <p>
    <strong>Name:</strong>
    <%= part.name %>
  </p>

</div>

app7/app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Show this part", @part %> |
  <%= link_to "Back to parts", parts_path %>
</div>

app7/app/views/parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parts</h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
    <p>
      <%= link_to "Show this part", part %>
    </p>
  <% end %>
</div>

<%= link_to "New part", new_part_path %>

app7/app/views/parts/new.html.erb
<h1>New part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Back to parts", parts_path %>
</div>

app7/app/views/parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @part %>

<div>
  <%= link_to "Edit this part", edit_part_path(@part) %> |
  <%= link_to "Back to parts", parts_path %>

  <%= button_to "Destroy this part", @part, method: :delete %>
</div>